- hosts: localhost
  vars:
    pulplift_name: zest-builder
    pulplift_boxes:
       zest-builder:
         box: pulp3-sandbox-centos7
  roles:
    - pulplift

- hosts: zest-builder
  vars:
    gem_version: 0.0.2
  roles:
    - zest_pulp3_build
