---
- name: 'Write box file'
  copy:
    dest: "{{ current_directory }}/vagrant/boxes.d/80-tmp-{{ pulplift_name }}.yaml"
    content: "{{ pulplift_boxes | to_yaml }}"

# using --no-parallel here to avoid problems with libvirt storage volumes
# see https://github.com/vagrant-libvirt/vagrant-libvirt/issues/850
- name: 'Bring up boxes'
  command: "vagrant up --no-parallel {{ pulplift_boxes.keys()|join(' ') }}"
  args:
    chdir: "{{ current_directory }}"
